apiVersion: apps/v1
kind: Deployment
metadata:
  name: k9s
  labels:
    app: k9s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k9s
  template:
    metadata:
      labels:
        app: k9s
    spec:
      containers:
      - name: k9s
        image: ghcr.io/derailed/k9s-headless:latest
        args:
          - "--headless"
          - "--readonly"
        ports:
        - containerPort: 8080