wordpressUsername: admin
wordpressPassword: admin123
service:
  type: ClusterIP
persistentVolumeClaim:
  enabled: true
mariadb:
  enabled: true
ingress:
  enabled: true
  hostname: wordpress.local
  annotations:
    kubernetes.io/ingress.class: nginx