service:
  type: ClusterIP
  
ingress:
  enabled: false

mariadb:
  enabled: true
  auth:
    rootPassword: "dev-root-password"
    password: "dev-wp-password"
    username: "bn_wordpress"
    database: "bitnami_wordpress"
  primary:
    persistence:
      enabled: true
      storageClass: ""
      size: 8Gi
    podAnnotations:
      "helm.sh/resource-policy": keep

persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
